[package]
name = "my-blaster-runs-hot"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0", features = ["dynamic"] }
num-derive = "0.3.3"
num-traits = "0.2.15"
rand = "0.8.5"

[workspace]
resolver = "2"